In [ ]:
%%bash
wget https://www.w3schools.com/python/pandas/data.csv

--2024-10-22 23:47:57--  https://www.w3schools.com/python/pandas/data.csv
Resolving www.w3schools.com (www.w3schools.com)... 192.229.173.207
Connecting to www.w3schools.com (www.w3schools.com)|192.229.173.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2858 (2.8K) [application/octet-stream]
Saving to: ‘data.csv.1’

     0K ..                                                    100% 71.3M=0s

2024-10-22 23:47:57 (71.3 MB/s) - ‘data.csv.1’ saved [2858/2858]

In [ ]:
# Ways to generate pandas DataFrame

# Make sure to import library as pd
import pandas as pd

# Define by Dictionary
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

# Keys: calories, duration
# Values: [420, 380, 390], [50, 40, 45]

data

{'calories': [420, 380, 390], 'duration': [50, 40, 45]}

In [ ]:
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
df2 = pd.read_csv('data.csv')
df2

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# Pull Column
df2["Duration"]

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [ ]:
# Pull Row
df2.loc[0]

Duration     60.0
Pulse       110.0
Maxpulse    130.0
Calories    409.1
Name: 0, dtype: float64

In [ ]:
# Manipulate Info in DataFrame

# Pull certain values in column

# (Only get entries with duration 60)
df2[df2["Duration"]==60]

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
5          60    102       127     300.0
6          60    110       136     374.0
..        ...    ...       ...       ...
157        60    100       120     270.4
158        60    114       150     382.8
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2

[79 rows x 4 columns]

In [ ]:
# Add more than one condition

# (Only get entries with duration 60 and pulse greater than 110)
df2[(df2["Duration"] == 60) & (df2["Pulse"]>110)]

     Duration  Pulse  Maxpulse  Calories
1          60    117       145     479.0
22         60    130       101     300.0
35         60    114       140     415.0
43         60    111       138     400.0
44         60    111       131     397.0
49         60    111       139     397.6
53         60    118       151     486.0
55         60    121       146     450.7
56         60    118       121     413.0
116        60    116       141     443.0
122        60    119       169     336.7
124        60    111       151     368.5
129        60    114       151     384.0
144        60    136       170     470.2
147        60    112       146     361.9
155        60    111       151     368.5
158        60    114       150     382.8
166        60    115       145     310.2

In [ ]:
# Save it back into csv

df3 = df2[(df2["Duration"] == 60) & (df2["Pulse"]>110)]
df3.to_csv("filtered.csv")